# Generated by Django 3.2.9 on 2021-12-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
