# Generated by Django 3.2.9 on 2021-12-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nordhapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=32, upload_to='uploads/products/'),
            preserve_default=False,
        ),
    ]
